# Generated by Django 2.1.7 on 2021-01-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'ordering': ['-date_sent']},
        ),
        migrations.AddField(
            model_name='directmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
