# Generated by Django 2.1.7 on 2021-01-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0002_auto_20210111_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='is_read',
        ),
    ]
